#!/bin/bash

# First disable navigation processes
killall map_server
rosnode kill /map_saver
killall static_transform_publisher
rosnode kill /move_base

#rosrun cartographer_ros cartographer_occupancy_grid_node -resolution 0.05
#rosrun arlo start_trajectory /home/tjlw/ROS/catkin_ws/src/arlo/configuration_files/ arlo_cartographer_params.lua 0 0 0 0

